on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: Tech-Phantoms
          label: github-invitation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            <div align="center">
            <img src="https://user-images.githubusercontent.com/51391473/138764839-1011988e-66f2-4427-a8fc-e0380971df29.gif">
            <br>
            <h1>Welcome To Tech Phantoms ðŸŽ‰</h1>
            </div>
            <br>

            > Invitation sent to join the GitHub Organization. Check your mail to accept the invitation! ðŸ¤–

            ## About Us

            Tech Phantoms is a open source community run by students, together we work on cool project organize organize hackathons and also help and support new people in tech ðŸš€.

            Check out our [Twitter](https://twitter.com/tech_phantoms) and [Discord](https://discord.apihacks.co) to get involved with us! ðŸš€

        env:
          INVITE_TOKEN: ${{secrets.GOD_TOKEN}}
      - name: Discord Notiofication 
        uses: wei/curl@master
        with:
          args: -i -H "Accept:application/json" -H "Content-Type:application/json" -X POST --data '{"content":"[${{github.event.issue.user.login}}](${{github.event.issue.user.html_url}}) just opened an issue to join our GitHub ORG ðŸŽ‰ðŸŽ‰"}' ${{ secrets.DISCORD_INVITATION }}
          
